drush @avs.prod cc all
drush @gru.prod cc all
drush @shlz.prod cc all
drush @epo.prod cc all
drush @sb.prod cc all
drush @sur.prod cc all
drush @nfz.prod cc all
drush @wa.prod cc all
drush @ent.prod cc all
drush @reg.prod cc all
drush @fru.prod cc all
